### ISSUE TITLE
update list_variables()

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#103]
list_variables() doesn't include CMI, and perhaps other variables that are actually supported by climr.

**Comment by whmacken** [comment]
High importance and easy to fix.

**Comment by cmahony** [comment]
@CeresBarros are you able to add CMI? I'll start an enhancement issue for will's request for variable sets.

**Comment by kdaust** [comment]
Fixed in 6b11bc6 - sorry for the delay
