### ISSUE TITLE
run examples

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#114]
Most examples in the documentation are "protected" by a `\dontrun{}` but we could use them for package testing.

@kdaust is there a particular reason why these examples are protected? is it because they would take too long to run?

**Comment by kdaust** [comment]
No reason that I can think of - as long as we keep to < 1000 points and fairly small geographical regions it should be super fast. That being said, most of the examples there are outdated, and I (we) should make new ones

**Comment by CeresBarros** [comment]
I've added a "to do" label to reflect the needed updates to examples

**Comment by CeresBarros** [comment]
@kdaust, @cmahony

I forgot that CRAN tests no longer "respect" the `\dontrun{}` on examples anymore. Meaning that things like

```
​#' @examples
#' \dontrun{
#' calc_DD_above_18(2, -14, "All")
#' }
```

will fail on GitHub Actions when using `r-lib/actions/check-r-package@v2` when the functions are not being exported.

We have a few options:

1. we remove the examples and move them to `testthat` scripts
2. we precede function calls int eh examples with `climr:::` 
3. we export functions

I _think_ no. 3 is not a good option, and no. 1 is the best option. No. 2 is the quickest for now and could be a good temporary option.

Any thoughts?

**Comment by kdaust** [comment]
Oh interesting! I agree that 3 isn't a good option. I'm happy with either 1 or 2 - for now we could use `climr:::` as you suggest

**Comment by CeresBarros** [comment]
closing this issue as #109 already lists the need for improved examples in the To Do list
