### ISSUE TITLE
missing `list_gcm_ts` function definition

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#120]
@kdaust I can't find the definition for `list_gcm_ts` but it's used in `gcm.R`. Is this a deprecated function?

**Comment by CeresBarros** [comment]
From the `gcm_ts_input` documentation it seems that it should be using `list_gcm` -- please confirm :)

**Comment by kdaust** [comment]
Initially I was thinking we might need a different set of GCMs for timeseries, but I think it's best to keep things consistent, so let's use `list_gcm`. We should change that in gcm_ts_input

**Comment by CeresBarros** [comment]
fixed in #124
