### ISSUE TITLE
Warning in `downscale` example

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#121]
In the example (which I've modified slightly) of `downscale` I'm seeing this warning:

```
dbCon <- data_connect()
xyz <- data.frame(lon = runif(10, -140, -106), lat = runif(10, 37, 61), elev = runif(10))
## get bounding box based on input points
thebb <- get_bb(xyz)
normal <- normal_input(dbCon = dbCon, bbox = thebb, cache = TRUE)

Downloading new data...
..................Caching data...
Warning messages:
1: In FUN(X[[i]], ...) : Empty tile - not enough data
2: In FUN(X[[i]], ...) : Empty tile - not enough data
3: In FUN(X[[i]], ...) : Empty tile - not enough data
```

I see data in `normal`, so it's not clear where the warning is coming from.
```
> normal
class       : SpatRaster 
dimensions  : 350, 650, 73  (nrow, ncol, nlyr)
resolution  : 0.04166667, 0.04166667  (x, y)
extent      : -139.6042, -112.5208, 41.557, 56.14033  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source(s)   : memory
names       : PPT01, PPT02, PPT03, PPT04, PPT05, PPT06, ... 
min values  :     6,     3,     8,     9,     3,     8, ... 
max values  :  1130,   919,   858,   600,   464,   382, ... 
```

This is not urgent, but we should figure out what is issuing the warning and how to avoid it -- not great to have these warnings in doc examples.

**Comment by CeresBarros** [comment]
I don't think the warning needs to be removed -- it can be useful.
But it shouldn't be triggered in the example _unless_ the example is _meant_ to show it (in which case the example needs a commented line explaining this).

So the question is: do we want to talk about this warning in the example? If not, then can we change the bbox so that the warning isn't triggered?

**Comment by kdaust** [comment]
I'd say we probably don't want to show it in the example - so we just need to choose points whose bounding box is fully inside BC

**Comment by CeresBarros** [comment]
Can you take care of that please?

**Comment by CeresBarros** [comment]
#207

**Comment by CeresBarros** [comment]
this script is no longer needed
