### ISSUE TITLE
`historic_input` and `gcm_input_postgis` output a list, not a SpatRaster

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#122]
From the documentation, it is suggested that these two functions output a `SpatRaster` stack, but they are instead outputting a list of length = 1 with the SpatRaster. 
The documentation needs to be fixed.

**Comment by kdaust** [comment]
I think that is the expected behaviour - at least for gcm_input_postgis, it should return a list with a SpatRaster for each gcm

**Comment by CeresBarros** [comment]
I'll make the doc clearer in that regard.

**Comment by CeresBarros** [comment]
Oh, could we add `names()` to the list according to GCM?

**Comment by kdaust** [comment]
Yes that's a great idea

**Comment by CeresBarros** [comment]
closing as documentation issue was addressed in d80b3a37a56d6e92a8235dadb998957d86c9d70a
