### ISSUE TITLE
Awkward labelling in SpatRasters returned by `historic_input`

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#123]
Notice some raster layers with very loooooooong labels

![image](https://github.com/bcgov/climr/assets/22214224/7e77117e-716e-4b97-a82a-6cd3978425a9)

**Comment by kdaust** [comment]
I'm not sure this is a huge deal - I guess we could round the anomalies before sending to postgres?

**Comment by CeresBarros** [comment]
It's not a huge deal, but it suggests funky data. (even if it's not). the "crazy" labels only show up when the layer shows mostly missing data... what is happening there? why are there two green "blobs" in the maps with long labels?

**Comment by cmahony** [comment]
something is very wrong with those two layers (PPT02 & PPT07). they should look like the other layers.

**Comment by kdaust** [comment]
Yes good point. I'll investigate tomorrow - thanks for catching!

**Comment by kdaust** [comment]
@CeresBarros do you remember which GCM/period/scenario that was for?

**Comment by CeresBarros** [comment]
I can't recall the specifics as I was simply trying to get the example of `downscale` to run. Use the code now in the devl branch and inspect the normal and historic rasters (can't remember which was the source of the figure). Or I can have a look tomorrow.
On 13 Dec 2023, at 22:15, Kiri Daust ***@***.******@***.***>> wrote:

@CeresBarros<https://github.com/CeresBarros> do you remember which GCM/period/scenario that was for?

**Comment by CeresBarros** [comment]
@kdaust reprex to the figure:
```
dbCon <- data_connect()
xyz <- data.frame(lon = runif(10, -140, -106), lat = runif(10, 37, 61), elev = runif(10))

## get bounding box based on input points
thebb <- get_bb(xyz)
historic <- historic_input(dbCon, thebb)
terra::plot(historic[[1]])
```

**Comment by kdaust** [comment]
Thanks Ceres!

**Comment by cmahony** [comment]
@kdaust has this been resolved?

**Comment by kdaust** [comment]
Yep its fixed :) 
![image](https://github.com/bcgov/climr/assets/34073038/6b4dde13-d8f7-4a91-b9a7-960e556bf4eb)
