### ISSUE TITLE
Adding spatial output options to `downscale`

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#131]
I was wondering if it'd make sense to add an option to output the downscaled variables as a spatial object instead of a `data.table`. Perhaps a vector object?

I only foresee one issue at this point, which is the lat of projection/spatial metadata info in the `xyz` input object. A solution would be to add `bbox` as an optional argument (from which we'd extract spatial metadata) or a CRS argument.

Thoughts?

**Comment by kdaust** [comment]
That would probably make sense  - would we use sf or terra? So far I've found sf is faster  for vector data than terra, but would require adding another dependency. Also - would this be related to providing optional raster output for downscaled variables?

Re: crs, it's required  that the input is in epsg:4326, so I think we can just output in that projection.

**Comment by CeresBarros** [comment]
I would use `terra` as we're not going to do spatial operations, just convert the `data.table` to a spatial object.

Good to know about the CRS. That should be documented and checked accordingly -- I'll take care of that.

**Comment by CeresBarros** [comment]
done in #144
