### ISSUE TITLE
`normal_input`/ pgGetTerra` fail when `bbox` and `boundary` `= NULL`

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#134]
The function shouldn't fail when passing the default argument. I had also understood that if no boundary is selected the full dataset is output.

Here's a reprex:
```
 dbCon <- data_connect()
 normal_nobb <- normal_input(dbCon = dbCon, cache = TRUE)
```

**Comment by kdaust** [comment]
Yes true - for most purposes it's unlikely to be called without a bounding box, but I'll fix that.

**Comment by kdaust** [comment]
We've decided to make bbox required

**Comment by kdaust** [comment]
Fixed in https://github.com/bcgov/climr/commit/5f48e97c3ab7bca35ca87477084cc25c39c98a6c
