### ISSUE TITLE
Bypassing server checks for individual runs

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#143]
At the moment, `climr` checkss for available GCM/run/scenario data on the server and then compares it to cached data to figure out whether downloads are necessary.

This has the inconvenience of failing when the server is down or an internet connection is not available, even if the all necessary data have been cached.

A solution could be to build an rds file with all the run data available on the server during pkg installation and use it to bypass server checks.

**Comment by kdaust** [comment]
Done. climr checks on load if the run data is downloaded, and if not, it downloads and caches it. As long as all necessary data is cached, downscale should work fine without connection to server.

**Comment by CeresBarros** [comment]
fixed in 18d407dd725a87187a1c381a562b83017c000738
