### ISSUE TITLE
NAs returned for Haida Gwaii in observed 2001_2020 period. 

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#151]
@kdaust when i run climr for 1961-1990 observed it returns all locations. when i run it for 2001-2020 observed it returns NaN for most of Haida Gwaii and a small corner of NW BC. i haven't tried it for GCMs. perhaps this is the root of the Haida Gwaii enigma in the CCISS tool??
this problem can be replicated by running the CCISS_Spatial_exports.R file down to line 359 (pushed to main in CCISS_ShinyApp). 

2001-2020 hist bgc predictions
![hist](https://github.com/bcgov/climr/assets/17104005/58531d45-5785-4ed7-b304-710d36fe6856)

1961-1990 bgc predictions
![ref](https://github.com/bcgov/climr/assets/17104005/a71f3985-7b6e-4bf8-abb6-d02db6062402)

**Comment by kdaust** [comment]
Nice catch Colin! I'll investigate

**Comment by CeresBarros** [comment]
@cmahony if we always expect NAs to be in the same places between the normals period and the historic 2001-2020, this should become a test.

**Comment by cmahony** [comment]
> @cmahony if we always expect NAs to be in the same places between the normals period and the historic 2001-2020, this should become a test.

@CeresBarros sounds good. NAs should be in the same places across all periods (GCMs too). also, i got one NA in the reference period downscaling and we should investigate that too.

**Comment by CeresBarros** [comment]
@cmahony can you whip up a reprex that gets all runs/periods/GCMs/etc into a/several SpatRaster/s that i can then use to make the test?

**Comment by cmahony** [comment]
> @cmahony can you whip up a reprex that gets all runs/periods/GCMs/etc into a/several SpatRaster/s that i can then use to make the test?

@CeresBarros does this do the trick? @kdaust there are a few problems that show up with this example:

- [ ] the BC PRISM is superimposed onto the ClimateNA North America mosaic. this creates boundary artefacts. instead, if the study area spans the BC boundary (as in this case), climr should use only the mosaic. we shouldn't be mixing reference climatologies. 
- [ ] the 2001_2020 observed climate is limited to the PNW and truncates Haida Gwaii. 
- [ ] the GCM (ACCESS-ESM1 in this example) is limited to PNW (though a larger PNW than the 2001_2020 layer). 
- [ ] the caching didn't seem to work. when i ran the downscale a second time it downloaded all over again... about 10 minutes of downloading). 

```
#reproducible example of basic downscaling at North america scale

library(terra)
library(climr)

# create the input DEM
dem <- rast("tests/GTOPO30.tif") #30-arcsecond DEM of north america. pushed to "tests" folder on climr main
dem <- aggregate(dem, fact=4) #upsample to 2-arcminute

## make the climr input file
points <- as.data.frame(dem, cells=T, xy=T)
colnames(points) <- c("id", "x", "y", "el")
points <- points[,c(2,3,4,1)] #restructure for climr input
str(points)

#climr outputs for reference period, recent, and one GCM simulation
var <- "Tmax01"
clim <- climr_downscale(points,
                        which_normal = "auto",
                        gcm_models = list_gcm()[1],
                        ssp = list_ssp()[2],
                        gcm_period = list_gcm_period()[2],
                        max_run = 1L,
                        historic_period = "2001_2020",
                        return_normal = TRUE,
                        vars = var
)

# compare extent of downscaled values for each of the layers
X <- dem
values(X) <- NA
X[clim[PERIOD=="1961_1990",ID]] <- clim[PERIOD=="1961_1990",get(var)]
plot(X)
values(X) <- NA
X[clim[PERIOD=="1961_1990",ID]] <- clim[PERIOD=="2001_2020",get(var)]
plot(X)
values(X) <- NA
X[clim[RUN=="ensembleMean",ID]] <- clim[RUN=="ensembleMean",get(var)]
plot(X)
values(X) <- NA
X[clim[RUN=="r10i1p1f1",ID]] <- clim[RUN=="r10i1p1f1",get(var)]
plot(X)
```

**Comment by CeresBarros** [comment]
thanks @cmahony , I'll have a look tomorrow.
Quick thought about caching: are you using the latest commit on @devl? @kdaust made a recent change that may (or not help).

**Comment by cmahony** [comment]
> Quick thought about caching: are you using the latest commit on @DevL? 

@CeresBarros, no. i'd need you to show me how.

**Comment by CeresBarros** [comment]
for future reference:
at the top of your script you can add:
```
remotes::install_github("bcgov/climr@devl")
library(climr)
```

Make sure you do this from a fresh R session.

**Comment by cmahony** [comment]
@kdaust @CeresBarros this haida gwaii bug is still there in the new version of climr. My guess is that it is a problem with the anomaly surface being used to generate the 2001-2020 normals. i'll provide new anomaly surfaces.

**Comment by cmahony** [comment]
i created a set of anomaly surfaces relative to 1961-1990 and moved all anomaly surfaces to //objectstore2.nrs.bcgov/ffec/TransferAnomalies/ (these anomalies are using the CRU TS v4.05 for temperature and GPCC v2020 for precipitation). 
next step is for @kdaust to update the calculation of 2001-2020 normals based on these new anomalies. if easy enough, it would also be nice to have some of the other normals added to climr as well (e.g., 1951-1980, 1981-2010, 2011-2020, etc).

**Comment by cmahony** [comment]
@kdaust added the new anomaly surface to climr and it fixed the issue.
