### ISSUE TITLE
Return georeferencing of lat/long/elev of submitted points

### ISSUE THREAD

**Issue by whmacken** [bcgov/climr#159]
Need to return point georeferencing with the climr_downscale data. 
This information is required for models that need spatial awareness of points to account for spatial autocorrelation etc.

**Comment by CeresBarros** [comment]
Do you mean a spatial points object like a `SpatVector`?

**Comment by whmacken** [comment]
Simply a data frame of training points.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CeresBarros** [comment]
Would adding columns with point ID lat and long to the current output tables be a good option in your view? or are you thinking of a separate data.frame and then outputting a list with the two data.frames? Personally I prefer the first option as the user can then immediately work with the data.frame and the geographical information in one go.

**Comment by whmacken** [comment]
Yes adding columns. A function parameter to allow retaining all submitted columns might be a good option.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cmahony** [comment]
if i understand this correctly i wouldn't use that for my own workflows, since it would be so much redundant data. however, if it's a parameter in the climr functions then that seems like a way to serve everybody's needs.

**Comment by kdaust** [comment]
Since Ceres has already implemented the option to return a spatial object, and it's easy to extract the coordinates from that, is this necessary? I don't think we want to make redundancies...

**Comment by cmahony** [comment]
@whmacken, since the input table to downscale() has id, lat, lon, el, why would the output table need to have it as well?

**Comment by whmacken** [comment]
Because the ID do not necessary match between input and output

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cmahony** [comment]
what? ok that's a problem. @kdaust?

**Comment by whmacken** [comment]
Just allow inclusion of input columbs as a parameter option and it’ll never be a problem

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cmahony** [comment]
well. the input and output id must also match, otherwise, what's the point of an id?

**Comment by CeresBarros** [comment]
> Because the ID do not necessary match between input and output

I believe I've fixed that in the `devl` branch for parallel mode. Were the IDs also being screwed up in sequential mode @whmacken ?
Can you provide a reprex?

**Comment by CeresBarros** [comment]
> Since Ceres has already implemented the option to return a spatial object, and it's easy to extract the coordinates from that, is this necessary? I don't think we want to make redundancies...

true, but I agree with Will that if a data.table/frame is the selected output, then the IDs MUST align with the input IDs and, perhaps optionally adding other columns could be useful. I don't know we should add ALL additional columns though. At some point the user may just need to join the input and output tables (or the output table with another one that has other point attributes by ID).

I wonder, however, if the ID column should become mandatory to force the users to be consistent with their point IDs and ourselves in respecting them

**Comment by whmacken** [comment]
Most of my IDs are not numerical. Please, please allow submitted columns to be returned as a parameter such as keep_all = TRUE.

**Comment by CeresBarros** [comment]
> Making it a required input would make sense, although I'm fairly ambivalent.

I agree. In the end it's about how much you want to force users to do things your way, which requires very good documentation.

I think a `keep_all` arg is fine and can be implemented both the spatial and non-spatial output types. I would add that in the case where the `ID` column is _not_ supplied by the user it should be used internally but perhaps not returned? Won't users find it strange that they now have a new column?

**Comment by cmahony** [comment]
i believe we should always have a numeric ID column, and require one for input. the reason is that data.table sometimes (unpredictably, to me at least) changes row order during operations, and so the id field is essential.

**Comment by kdaust** [comment]
@cmahony I agree - also a unique numeric id field is required for the downscaling calculation anyway. Currently we create one if it doesn't meet the standards, and then don't return the other columns (because the join may not work). If a unique numeric ID is supplied, then it will return all columns

**Comment by cmahony** [comment]
resolved
