### ISSUE TITLE
fill in missing documentation details

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#171]
Many TODO's still left in documentation sections. @kdaust I've reached the limits of my knowledge and will need your input to fill these in

**Comment by cmahony** [comment]
@kdaust i'm also happy to fill out any you'd rather leave to me.

**Comment by CeresBarros** [comment]
@cmahony, @kdaust, when you get to this, could you do the following in this order:
1.  looking at exported functions (Ctrl+Shift+F -> "@export" ) and revising all their documentation and filling in any gaps.
2. if you have time, do the same for non-exported functions that have documentation files (i.e. that DO NOT have "@noRd")
3. finally, have a look at the remaining functions with "@noRd". I strive to document all my functions, regardless of their visibility to users -- makes continued development easier when developers change :)

**Comment by CeresBarros** [comment]
@cmahony, @kdaust, please see list bellow:

Functions **urgently** needing documentation -- please check `@description` and `@details` sections, complete and add them as necessary.

- [ ] `normal_input()`
- [ ] `historic_input`
- [ ] `historic_input_ts`
- [ ] `gcm_input`
- [ ] `gcm_ts_input`
- [ ] `gcm_hist_input`
- [ ] `downscale`
- [ ] `climr_downscale`
- [ ] `lapse_rate`
