### ISSUE TITLE
list_variables() - create options for selecting variable sets by annual, seasonal, and/or monthly

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#175]
this is a minor enhancement but it will be convenient for users. we can add option `set=c("all", "monthly", "seasonal", "annual")` where
```
monthly <- list_variables()[grep("01|02|03|04|05|06|07|08|09|10|11|12", list_variables())]
seasonal <- list_variables()[grep("wt|sp|sm|at", list_variables())]
annual <- list_variables()[-which(list_variables()%in%c(monthly, seasonal))]
```
@CeresBarros let's do this together on wednesday as a way for me to learn how to do a pull request.

**Comment by kdaust** [comment]
Done in 6b11bc6 (sorry Colin - you'll have to choose a new issue - made sense for me to fix it while I was there)
