### ISSUE TITLE
Message user about "silly" argument combos

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#178]
Tell the user when some argument combinations do not make much "sense". Here's an initial list:

- [x] passing several GCM models to `climr_downscale(..., gcm_models)`, but no choice of future period or years.
- [x] passing a choice of future period/years but no GCM(s)
- [x] passing a choice of SSPs but no GCM(s)

**Comment by CeresBarros** [comment]
Can you think of any others @kdaust ?

**Comment by kdaust** [comment]
A couple others:

- specifying a future period/years or gcm_ts_years but not specifying any gcm_models
- specifying a gcm_models but setting ssp to null (unlikely since the default is all ssp)
- specifying max_run without a gcm_model - not that it will make any difference, it will just be ignored.

**Comment by CeresBarros** [comment]
> specifying a gcm_models but setting ssp to null (unlikely since the default is all ssp)

I'm adding argument checks which _can_ prevent the user from passing a NULL -- do we want to allow NULL for `ssp`?

**Comment by kdaust** [comment]
Good question - probably not, although NULL would be fine for just observational (and modelled historic) data

**Comment by CeresBarros** [comment]
I'll leave it as a "no NULL allowed" for now and we can change later if need be

**Comment by CeresBarros** [comment]
closing as complete
