### ISSUE TITLE
replace the composite climatology

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#182]
the transfer anomalies that i used to transfer the climatologies from 1981 to 1961 had an error in them. I need to correct them, and then @kdaust will need to replace them in the climr database

**Comment by cmahony** [comment]
@kdaust i've uploaded the corrected composites to \\objectstore2.nrs.bcgov\ffec\Climatologies\climr_composite

**Comment by kdaust** [comment]
@cmahony done. The updated normal is called "normal_composite"
