### ISSUE TITLE
Data files in `tests/` are not being used?

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#184]
The `.tif` and `.csv.` files in `tests/` do not seem to be used anywhere (a Ctrl+Shift+F didn't find their filenames being used). Do we still need them?

**Comment by cmahony** [comment]
@CeresBarros, agreed. i believe you can delete them. Bruno and I used them for testing the first version of climr buth they aren't needed anymore.

**Comment by cmahony** [comment]
deleted.
