### ISSUE TITLE
remove white space and resize figures in vignettes

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#185]
I couldn't figure out how to remove the white space surrounding figures in RMarkdown, and to resize multipanel figures. example below. Flagging this as a to-do.  @CeresBarros if you know how to do this, lmk. 

![image](https://github.com/bcgov/climr/assets/17104005/3ebb664b-211f-4ad2-925e-20b66aa9c4ec)

**Comment by CeresBarros** [comment]
Will get to this ASAP.

**Comment by CeresBarros** [comment]
@cmahony figures should be good now, but do let me know if not
