### ISSUE TITLE
naming conventions for time series parameters in climr_downscale()

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#191]
the naming for time series parameters in climr_downscale() doesn't follow a convention: gcm_hist_years, gcm_ts_years, historic_ts

here is my recommended convention: obs_hist_years, gcm_hist_years, gcm_ssp_years. 

I recognize this carries risks of breaking the package. perhaps we should make this change as part of a comprehensive rationalization of the naming conventions throughout climr.

**Comment by CeresBarros** [comment]
a similar issue happens with input point data arguments. 

e.g. `climr_downscale` and `downscale` have an argument called `xyz`, but in `get_bb` the argument is `in_xyz`. Although `get_bb` doesn't _need_ elevation or ids, I find it confusing to have various versions of similar arguments. We should either make their names more different, or force the two arguments to be of the same type.

**Comment by CeresBarros** [comment]
@cmahony, @kdaust package breakage may be avoided with a careful "search all" (Ctrl+Shift+F)

**Comment by cmahony** [comment]
closing this issue as redundant. i moved these points over to issue #196
