### ISSUE TITLE
sub in updated mosaics (composite climatologies)

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#195]
I've revised the mosaics (composite climatologies). the primary change is in the prairies: removal of line artefacts and a new dataset for precipitation. i've also removed some small artefacts over ocean in puget sound. 
@kdaust there is no hurry to sub these into climr, as it will not affect BC very much and the existing mosaics are sufficient for our experimental BGC modeling. However, it would be good to get these into climr when convenient as they are a better product.  

i've replaced the old with new in \\objectstore2.nrs.bcgov\ffec\Climatologies\climr_composite

you can view images of the mosaics in [here](https://bcgov-my.sharepoint.com/:f:/r/personal/colin_mahony_gov_bc_ca/Documents/Projects/2024_intercomparison/results?csf=1&web=1&e=g4MOD6).

**Comment by kdaust** [comment]
Done
