### ISSUE TITLE
Minor fixes for v0.0.3 website

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#211]
running list of a few small things that can improve the v0.0.3 website: 

- [x] remove the "caching" vignette, or move to end of list. (ceres)
- [x] change order of the vignettes to beginner, intermediate, rasters, methods, lapse rates. (ceres)
- [x] minor edits to readme and climr-package.html (colin)
- [x] in funtion reference list, move utilities section above data section. 
- [x] in function reference, move lapse_rate() into utilities section
- [x] in function reference, sort descending in order of function importance (e.g., the list_*() functions should be at the top, not the bottom) (ceres)
- [x] revise title of downscale() (Colin)

**Comment by CeresBarros** [comment]
#212

**Comment by CeresBarros** [comment]
> in function reference, sort descending in order of function importance (e.g., the list_*() functions should be at the top, not the bottom) (ceres)

@cmahony I think you're better placed than I am to do that. I'll show you how after I deal with the other points

**Comment by cmahony** [comment]
@CeresBarros thanks for this. i made two commits and [pull request #215](https://github.com/bcgov/climr/pull/215) is ready to merge.

**Comment by cmahony** [comment]
complete
