### ISSUE TITLE
gcm data is limited to PNW

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#213]
library(rworldmap)
data("countriesCoarse")

par(mar=c(1,1,1,1), mfrow=c(3,5))
for(i in 1:length(list_gcm())){
dbCon <- data_connect() 
gcm <- gcm_input(
  dbCon = dbCon, 
  bbox = c(80, 20, -50, -170),
  gcm = list_gcm()[i], 
  ssp = list_ssp()[2],
  period = list_gcm_period()[2],
)

plot(countriesCoarse, xlim=c(-170, -50), ylim=c(20,80), main=list_gcm()[i])
plot(gcm[[1]][[1]], add=T, legend=F)
}

![Rplot](https://github.com/bcgov/climr/assets/17104005/2408275c-3a2d-4dad-9dc6-c532727d8714)

**Comment by kdaust** [comment]
![image](https://github.com/bcgov/climr/assets/34073038/e47bf023-18bd-4d9e-a348-81800fdb973c)
Fixed in https://github.com/bcgov/climr/commit/5c3968baf120b71c42123c244b0e8e208e288acf

**Comment by cmahony** [comment]
@kdaust i tried the reprex but it crashed midway and appears to have broken the server connection. can you try? 

![image](https://github.com/bcgov/climr/assets/17104005/976f75f7-89f2-405b-aef5-42c6ca7dc090)

> library(climr)
Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>,  : 
  NULL value passed as symbol address
Downloading and Caching ESM run info :)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘poolClose’ for signature ‘"NULL"’
In addition: Warning messages:
1: In value[[3L]](cond) :
  Could not connect to database. Will try using cached data.
2: In fun(libname, pkgname) :
  Could not connect to server. Only cached normal periods will be available.

**Comment by cmahony** [comment]
i got it to run again but it crashed in the same iteration.

**Comment by kdaust** [comment]
I'll take a look shortly

**Comment by kdaust** [comment]
@cmahony Ok so the reason the server was crashing was due to how you were pulling the data - you were opening new database connections inside the loop and never closing them, so after a while it overwhelmed the server. I did find an issue with MIROC6 though, which is now fixed. 

Reprex: 
```
library(rworldmap)
library(climr)
library(pool)
data("countriesCoarse")

par(mar=c(1,1,1,1), mfrow=c(3,5))
dbCon <- data_connect()
gcm <- gcm_input(
  dbCon = dbCon,
  bbox = c(80, 20, -50, -170),
  gcm = list_gcm(),
  ssp = list_ssp()[2],
  period = list_gcm_period()[2],
)

for(i in 1:length(list_gcm())){
  plot(gcm[[i]][[7]], legend=F, main=list_gcm()[i])
  plot(countriesCoarse, add = T, xlim=c(-170, -50), ylim=c(20,80))
}
poolClose(pool)
```
Output: 
![GCM_Periods](https://github.com/bcgov/climr/assets/34073038/976767f4-b0c7-4f5c-9679-01edc076a028)
