### ISSUE TITLE
plan for v0.0.4 release

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#222]
@kdaust, great to see the north american normals in the database! is adding the 2011-2014 GCM years in the cards over the next couple of weeks? if not, i propose we go ahead with the v0.0.4 release without them and let them and my vignette be v0.0.5. The completed addition of the NorAm normals and the 2015-2020 gcm years is significant and is already needed by users. 
@CeresBarros depending on Kiri's response, what do you think of this approach?

**Comment by CeresBarros** [comment]
No strong feelings. We do need to have check passing before releasing 0.0.4 though.

**Comment by CeresBarros** [comment]
To do
- [ ] check test failures related to comparisons to `main` branch `downscale` outputs
- [ ] make sure plot bivariate bug is fixed
- [ ] merge #221 and #219

**Comment by cmahony** [comment]
@kdaust do you have time tomorrow (wednesday) to make a plan for the v0.0.4 release?

**Comment by kdaust** [comment]
Released!
