### ISSUE TITLE
user report of install problems

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#226]
This from Carlos Carroll. I tried a reinstall and it worked fine. 

> -----Original Message-----
> From: Carlos Carroll <carlos@klamathconservation.org> 
> Sent: Saturday, March 23, 2024 10:47 AM
> To: Mahony, Colin FOR:EX <Colin.Mahony@gov.bc.ca>
> Subject: RE: question re climr extent
> 
> [EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.
> 
> 
> I got it to install via downloading the zip file and install from local
> path:
> > install("d:\\climr-devl")
> 
> _____
> 
> Carlos Carroll, Ph.D.
> Klamath Center for Conservation Research PO Box 104 Orleans, CA 95556
> 
> -----Original Message-----
> From: Carlos Carroll <[carlos@klamathconservation.org](mailto:carlos@klamathconservation.org)>
> Sent: Saturday, March 23, 2024 10:17 AM
> To: 'Mahony, Colin FOR:EX' <[Colin.Mahony@gov.bc.ca](mailto:Colin.Mahony@gov.bc.ca)>
> Subject: RE: question re climr extent
> 
> Do you know why the climr update is failing me? Thanks.
> 
> > remotes::install_github("bcgov/climr@devl")
> Using GitHub PAT from the git credential store.
> Error: Failed to install 'climr' from GitHub:
>   HTTP error 401.
>   Bad credentials
> 
>   Rate limit remaining: 59/60
>   Rate limit reset at: 2024-03-23 18:14:08 UTC
> 
> 
> > remotes::install_github("bcgov/climr")
> Using GitHub PAT from the git credential store.
> Error: Failed to install 'climr' from GitHub:
>   HTTP error 401.
>   Bad credentials
> 
>   Rate limit remaining: 58/60
>   Rate limit reset at: 2024-03-23 18:14:08 UTC
> 
> _____
> 
> Carlos Carroll, Ph.D.
> Klamath Center for Conservation Research PO Box 104 Orleans, CA 95556
>

**Comment by CeresBarros** [comment]
The original error 
```
remotes::install_github("bcgov/climr")
Using GitHub PAT from the git credential store.
Error: Failed to install 'climr' from GitHub:
HTTP error 401.
Bad credentials
```

Suggests that the user's GitHub credentials or PAT are not configured properly on the local machine they are using. I suggets having a look at:
https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git
and
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens

**Comment by cmahony** [comment]
sent an email to carlos with this advice.
