### ISSUE TITLE
Update ClimateNA historical observed time series

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#227]
Tongli releasing a new version this April with 2023. we will then update our time series for this.

**Comment by cmahony** [comment]
ClimateBC/NA version 7.50 has been released. This new release includes the monthly data for 2023. 
Here are the links for downloading the new version:
https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmedia.forestry.ubc.ca%2FClimateNA%2FPackages%2FClimatena%2FClimatena_v750.zip&data=05%7C02%7Ccolin.mahony%40gov.bc.ca%7C995120a31f9b4528b0a608dc6b984ea8%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638503549527811547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=JA1yoMQIiu3oGx%2Fu5RIz1x9F%2BigdvYuiM1h4Nzl%2F6zQ%3D&reserved=0

**Comment by kdaust** [comment]
Done!
