### ISSUE TITLE
mailing list

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#228]
we need a way to let users know about new releases. 
options: 

- RSS feed
- manual
- others?

**Comment by CeresBarros** [comment]
This post has a few options that could be implemented via `FFEC-website`:
https://forbo7.github.io/forblog/posts/7_blog_subscriptions.html

Not sure we can implement the same options on a `pkgdown` website, but we could point users to FFEC-website to enroll the mailing list.

**Comment by cmahony** [comment]
We landed on doing this via subscribe to the github repo
