### ISSUE TITLE
climr returns multiple lines of data for some individual ids

### ISSUE THREAD

**Issue by whmacken** [bcgov/climr#229]
[US_TrainingPoints_07April2024.csv](https://github.com/bcgov/climr/files/14909233/US_TrainingPoints_07April2024.csv)
This TP file has 37, 646 records but returns 38, 245 climr records. The duplicated data for each id are not the same.
Run line:
clim_vars <- climr_downscale(coords, which_normal = "auto", vars = climr::list_variables(), return_normal = TRUE, cache = TRUE)

Noncritical : Warning: 'gcm', 'gcm_ts', 'gcm_hist', 'historic' and 'historic_ts' are missing. Nothing to downscale.

**Comment by kdaust** [comment]
Fixed in https://github.com/bcgov/climr/commit/60738df62ad04f0cf40e3bd9840a43e7b935e060

Will need to pull and rebuild from devl.

**Comment by cmahony** [comment]
what was the bug?

**Comment by kdaust** [comment]
climr was using a mask of BC instead of WNA to choose which points would be downscaled with your composite normal vs the NA normal. And because the mask didn't match the composite normal size, it was downscaling them twice
