### ISSUE TITLE
bug: climr cache retrieval fails for .gri files 

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#233]
per v0.0.4 news: "Fixed caching issue where it would fail for very larger numbers of layers (>65000) by saving as .gri binary files."

however, climr cache retreival is still expecting .tif. As a result, the downscale is failing. 

```
library(climr)
points_downscale_ref <- readRDS("C:/Users/CMAHONY/OneDrive - Government of BC/Projects/2023_climr/climr/tests/testthat/data/points_downscale_ref.rds")
pt <- points_downscale_ref
projected <- climr_downscale(pt, 
                             gcm_models = list_gcm()[3],
                             ssp = list_ssp()[c(1,2,4)],
                             max_run = 10,
                             gcm_hist_years = 1851:2014, 
                             gcm_ts_years = 2015:2100, 
                             vars = "Tmin07"
)
```
```
Welcome to climr!
Getting normals...
Retrieving from cache...
Retrieving from cache...
Retrieving from cache...
Downscaling!!
Warning message:
C:\Users\CMAHONY\AppData\Local/R/cache/R/climr/gcmts/gcmts_VAR_canesm5/e3c2ac46-7237-4f8b-a560-dfdbb82d19ab.tif: No such file or directory (GDAL error 4) 
```

**Comment by kdaust** [comment]
@cmahony is it actually failing? The warning message is expected - I have it set up to first check for a .tif file, and it it fails there, it checks for a .gri. It worked correctly when I just tried it. I could suppress the warning message so it doesn't confuse users?

**Comment by cmahony** [comment]
@kdaust you're right it's not actually failing. i recommend removing the warning message. a couple of questions: 

- should we just change all cached files to .gri for consistency, or is there an advantage to .tif when feasible? 
- is there is a chance that users with older caches of .tif time series could confuse climr if it is looking for .gri first?

**Comment by kdaust** [comment]
- No; .tif is much more compressed, so will take up less storage. I think it makes sense to just use .gri when necessary.
- No; it looks for .tif first. And also, any caches that would require .gri would have failed previously anyway

I'll suppress the warning message and then I think we're good

**Comment by kdaust** [comment]
Fixed in https://github.com/bcgov/climr/commit/3d9eecbfdebd8bc1b8f40382bc270a38507b57b3
