### ISSUE TITLE
10 minutes to cache 1 GCM for small area

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#234]
downloading new GCM ts data seems to take a long time. 9.4 minutes for 84Mb. doesn't seem right. 

```
library(climr)
points_downscale_ref <- readRDS("C:/Users/CMAHONY/OneDrive - Government of BC/Projects/2023_climr/climr/tests/testthat/data/points_downscale_ref.rds")
pt <- points_downscale_ref

start.time <- Sys.time()
projected <- climr_downscale(pt, 
                             gcm_models = list_gcm()[3],
                             ssp = list_ssp()[c(1,2,4)],
                             max_run = 10,
                             gcm_hist_years = 1851:2014, 
                             gcm_ts_years = 2015:2100, 
                             vars = "Tmin07"
)
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken
```
```
Welcome to climr!
Getting normals...
Retrieving from cache...
Downloading GCM anomalies
Precip...
Tmax...
Tmin...
Caching data...
Retrieving from cache...
Downscaling!!
> end.time <- Sys.time()
> time.taken <- end.time - start.time
> time.taken
Time difference of 9.443832 mins
```

**Comment by kdaust** [comment]
Agreed, although not a bug. The way postgres rasters work, they have to be processed one layers at a time, and since this query has ~70,000 layers, it takes a bit. This would be a good use for doing the extraction directly in postgres, since there aren't many points.

**Comment by cmahony** [comment]
ok this makes more sense now. i see a few actions related to this: 

- [ ] @cmahony to open an issue to write a vignette on climr speed for various tasks, and how users can navigate this best. 
- [ ] @kdaust to open an enhancement issue to investigate whether there is a way to improve this aspect of performance. 
- [ ] @cmahony to add this as a known issue in News

once these are done we can close this issue.

**Comment by kdaust** [comment]
@cmahony since I already have an issue open for doing the extraction directly in postgres, and you've completed your tasks, are we good to close this one?

**Comment by cmahony** [comment]
yup, closing
