### ISSUE TITLE
allow two observational time series datasets in the climr queries

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#243]
we have two datasets (cru_gpcc and climate_na) (eventually three, with ERA5) but currently a query can include only one. this is limiting: for example, the plot_timeSeries function can't include both time series if that isn't allowed in the climr query. it would be nice to be able to get both time series from on climr call. note this would also require that we identify the datasets in the output, which may require some restructuring. so it's not a quick fix i don't think. just somehting to keep in mind for V1.

**Comment by kdaust** [comment]
Implemented in https://github.com/bcgov/climr/commit/85630fd4fa408dd2994974655e75d2613a4ce533
Observational timeseries now contain a column called "DATASET", specifying climate.na or gru.gpcc
