### ISSUE TITLE
revise variable naming convention

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#246]
variable name components (elements and times of year) are inconsistent (tmax01 vs. tmax_wt). this is a real pain for scripted workflows. we need to change to underscore separation throughout. A related issue is the DD_0 and DD_18 have underscores in the element name; change these to "<" or some other distinct symbol.

**Comment by cmahony** [comment]
tasks: 

- [ ] updated the variable_ClimateBC.csv for new codes.
- [ ] rename variables_ClimateBC.csv
- [ ] check all formulas

**Comment by kdaust** [comment]
I think it's all working now, but keeping this open until I get the tests passing

**Comment by kdaust** [comment]
Yay!
