### ISSUE TITLE
Eref and CMD are NaN above ~68N latitude

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#286]
@kdaust i'm out of time but this needs an urgent fix. can you look into this? 

![image](https://github.com/bcgov/climr/assets/17104005/85dea479-17ce-4df2-bffe-d27e175490e8)

**Comment by kdaust** [comment]
Very weird. Yep will do

**Comment by cmahony** [comment]
@kdaust, i'm taking a quick look at the calc_Eref script. hopefully i can take the troubleshooting a bit further.

**Comment by cmahony** [comment]
This is an artefact of the Hargreaves Eref equation. 
line 64 in calc_Eref_CMD.R   `OM <- -atan(Z / sqrt(-Z * Z + 1)) + pi / 2` is solely related to latitude; the value of `-Z * Z + 1` becomes negative above a latitude of ~68N. 
i checked hargreaves 1985 and our script is correct. 
makes rough sense that Hargreave's Eref wouldn't be valid at high elevation. 
i havent' checked the behaviour in climateNA but i'll figure out what we should replace the NaNs with. 
@kdaust no need for action on your part at this point

**Comment by carloscarroll** [comment]
Eref values from ClimateNA seem valid even above 68 degrees (ie not 0, <0, or NaN). (see attached arbitrary example from CNRM-ESM2-1_ssp585_2071).
![eref](https://github.com/user-attachments/assets/59c86538-ffef-4708-bf17-455ab57a8bc9)

**Comment by cmahony** [comment]
![image](https://github.com/user-attachments/assets/1bd978b8-c45a-4b7f-806a-fe9e5f5f4a17)

**Comment by cmahony** [comment]
I may have found a solution. the OM value in the Hargreaves Radiation equations is dependent only on julian day and latitude. shown below, above the arctic circle these values limit out at the same values. 
![image](https://github.com/user-attachments/assets/4be8971e-e066-4fff-97b9-b137f6cb4e89)

if we set NaNs to these limit values (3.1 and 0), we get a credible monthly Eref beyond the arctic circle. 
![image](https://github.com/user-attachments/assets/0b267bc7-9a1a-470b-a288-d400e8a56476)

@carloscarroll I'll try to implement this fix tomorrow or wednesday.

**Comment by cmahony** [comment]
the fix didn't fully work. banding visible in climr. will have to keep troubleshooting this. 
![image](https://github.com/user-attachments/assets/49c417ea-3ca7-4b85-954b-5b4036446ede)

**Comment by cmahony** [comment]
strangely, it's working for all months except june and july. 
![image](https://github.com/user-attachments/assets/c1a792f8-dde1-44fc-af21-287d23f643ce)

**Comment by cmahony** [comment]
it's fixed now. 
![image](https://github.com/user-attachments/assets/e90cd01a-a904-42fd-9c26-9abe556d83cb)

**Comment by cmahony** [comment]
@carloscarroll this fix is pushed to the devl branch of climr. we will merge to main soon in the next few days, but in the meantime you can use the new version by installing `remotes::install_github("bcgov/climr@devl")`

**Comment by cmahony** [comment]
completed.
