### ISSUE TITLE
`plot.ensemble` / `plot_timeSeries` functions need checking 

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#290]
@cmahony I'm assuming you're the developer of `plot_timeSeries` and the (previously) internal function `plot.ensemble`. Apologies if I'm assigning the wrong person

In PR #289 I fixed a bunch of variable definitions and package imports that were missing from `plot_timeSeries` and moved `plot.ensemble` to an unexported function. This is because we should really avoid defining functions inside functions. It makes testing harder and can lead to hiding bugs.

So, `plot.ensemble` and `plot_timeSeries` arguments need to be checked. 

Namely it's unclear to me where the objects `element1`, `element2`, `yeartime1` and `yeartime2` are coming from.

**Comment by cmahony** [comment]
done
