### ISSUE TITLE
Southern mexico missing?

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#291]
running a north american raster through climr leaves a gap in southern mexico. i'm wondering if our normals are missing? @kdaust could you look into this?  

here is the input: 
![image](https://github.com/user-attachments/assets/322ee503-c2e9-4dfc-873a-694dff60f798)

here is the output (Mean annual temperature)
![image](https://github.com/user-attachments/assets/77ee9f3e-57ee-4bea-bd95-3c5cf4e7cd4c)

reprex:
```
dem <- rast("//objectstore2.nrs.bcgov/ffec/DEM/DEM_NorAm/dem_noram_lowres.tif")

my_grid <- as.data.frame(dem, cells = TRUE, xy = TRUE)
colnames(my_grid) <- c("id", "lon", "lat", "elev") # rename column names to what climr expects

## A simple climr query. This will return the observed 1961-1990 and 2001-2020 mean annual temperature (MAT) for the raster grid points. 
climr <- downscale(
  xyz = my_grid, which_refmap = "refmap_climatena", vars = list_vars())
)

X <- rast(dem) 
X[climr[, id]] <- climr$MAT 
plot(X)

```

**Comment by kdaust** [comment]
Confirmed - Southern Mexico is missing from the climatena normals. They'll need to be reprocessed.

**Comment by kdaust** [comment]
![image](https://github.com/user-attachments/assets/be20b439-8ce4-4b5d-b7ca-e8ec4e27905c)
fixed in https://github.com/bcgov/climr/commit/a5fcadfe767251b3980a5717574162fd7ffb6554
