### ISSUE TITLE
ClimateNA surface in climr is corrupted (due to use of ClimateNA raster output)

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#306]
there are artefacts in climr output using `which_refmap = "refmap_climatena"` (this is march Tmax)
![image](https://github.com/user-attachments/assets/62e38423-4dbd-4450-bcc4-62feb12f226a)

it isn't there using `which_refmap = "refmap_prism"`
![image](https://github.com/user-attachments/assets/b8c697b6-717b-472c-ab86-33949e2d944b)

note in general that the `which_refmap = "refmap_climatena"` looks blurry/ugly in general. 

it isn't a problem with ClimateNA point query output looks fine: 
![image](https://github.com/user-attachments/assets/872a5b5d-9c9d-4d35-a36c-3c77d9129b28)

@kdaust i recall that we determined that climr is using the ClimateNA raster output as the data for the climr surfaces? we should switch this to use the ClimateNA point query. 

here is the leaflet map. https://rpubs.com/cmahony/climr_climatena_comparison_Tmax_March

one last thing. it appears that these artefacts occur when `which_refmap = "auto"`, so i don't think that parameter is working like we want it to.

**Comment by kdaust** [comment]
Fixed
