### ISSUE TITLE
Downscaling for other countries

### ISSUE THREAD

**Issue by dorjismo** [bcgov/climr#311]
I'd like to know if the code could be used for downscaling for other countries, not only for N. America. I'd like to downscale for my country, Bhutan. 

Thanks.
Sangay

**Comment by cmahony** [comment]
Hi Sangay, yes, this open-source code base could be use to create a similar package for other areas of the world, but it would be a big project! i recommend you try the [ClimateAP](https://web.climateap.net/) software covering the Asia-Pacific region. it does many of the things climr does.
