### ISSUE TITLE
run_nm not working as expected

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#335]
in a query for future gcm data using run_nm, i'm getting the error `The following observed periods are not supported: r1i1p1f1`. 

reprex: 

```
> in_xyz <- data.frame(
+   lon = c(-127.7052, -127.6227, -127.5623, -127.7162, -127.1858, -127.125, -126.9495, -126.9550),
+   lat = c(55.3557, 55.38847, 55.28537, 55.25721, 54.88135, 54.65636, 54.6913, 54.61025),
+   elev = c(291, 296, 626, 377, 424, 591, 723, 633),
+   id = 1:8
+ )
> clim <- downscale(xyz = in_xyz, 
+                        which_refmap = "refmap_climr", 
+                        gcms = list_gcms()[1], 
+                        ssps = list_ssps()[2],
+                        gcm_periods = list_gcm_periods()[3], 
+                        run.nm <- list_runs_ssp(list_gcms()[1], list_ssps()[2])[3]
+ )
Welcome to climr!
Error in .checkDwnsclArgs(xyz, which_refmap, obs_periods, obs_years, obs_ts_dataset,  : 
  The following observed periods are not supported:
  r1i1p1f1
  Please see 'list_obs_periods' for list of supported periods.
```

**Comment by kdaust** [comment]
@cmahony should be `run_nm`. Also, use `=` in the downscale call. This works for me:
` clim <- downscale(xyz = in_xyz, 
                                           which_refmap = "refmap_climr", 
                                            gcms = list_gcms()[1], 
                                            ssps = list_ssps()[2],
                                            gcm_periods = list_gcm_periods()[3], 
                                            run_nm = list_runs_ssp(list_gcms()[1], list_ssps()[2])[3]
                     )`
