### ISSUE TITLE
Precipitation as Snow

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#67]
something wrong with precipitation as snow. it should be zero in summer but lots of snow happening in climR. e.g. in july below: 

![climR tests compareClimBC PAS07](https://user-images.githubusercontent.com/17104005/161088220-efdde418-aea5-4db7-9611-0dce8702ee5b.png)

winter PAS looks fine. 

![climR tests compareClimBC PAS01](https://user-images.githubusercontent.com/17104005/161088442-1873ccac-3145-4aec-8164-eb37d0d66a56.png)

**Comment by meztez** [comment]
do you think we have the same reversal problem?, values are always close to 95%

I've changed it, would you mind retesting?

Maybe take a close look at NFFD, it might be the same thing happening

**Comment by cmahony** [comment]
will do asap, but i can't retest until a few hours from now. will do asap

**Comment by cmahony** [comment]
@meztez NFFD was fixed but PAS still is the same as before

**Comment by meztez** [comment]
@cmahony I introduced a typo in the PAS formula this morning while testing the switch for b and T0. 

Fixed I believe

**Comment by meztez** [comment]
I've updated the parameters to use what Tongli provided. I think this is because of Tmin.

**Comment by cmahony** [comment]
I don't think it's Tmin because the climateBC values of Tmin are similar
