### ISSUE TITLE
PAS higher than climateBC

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#68]
PAS is higher in climR than in climateBC. i think this is probably the parameters; the parameters in the ClimateNA publication had some errors and tongli provided some WNA parameters that may not match these. Bruno corrected some errors in the published equations, but the parameters may still be an issue.

![climR tests compareClimBC PAS07](https://user-images.githubusercontent.com/17104005/161147822-4784e7a0-4710-4e38-a90d-c1ac10ee8e06.png)

**Comment by kdaust** [comment]
Hopefully this has been fixed by change the precipitation anomalies to percentages instead of differences

**Comment by cmahony** [comment]
Yes, let's give it a look when i produce the test plots. however, there is a related issue that there doesn't seem to be an elevation adjustment applied to PAS. because temperature is a factor in PAS, we would want to see the fine-scale topographic structure that is apparent in climateBC but not in climr in this plot. if this persists in the new test plots i will open a new issue for that.

**Comment by cmahony** [comment]
Scratch that last comment. I remembered that these plots were also confounded by an error in climateBC that resulted in no elevation adjustment of Tmin. I recall it is fixed now so the new plots shouldn't have this problem.

**Comment by cmahony** [comment]
reopening this issue because there are still problems with PAS.

**Comment by cmahony** [comment]
see also the preceding issue: https://github.com/bcgov/climr/issues/67

**Comment by cmahony** [comment]
from tongli two years ago

```
Hi Colin,

Nice to the progress. I will have a try on it.
I realized that there were several errors in the formulas in the paper. Here is the code for NFFD in use:
'NFFD_wna-------------------->
        NFFD_wna(1) = 34.742 / (1 + Math.Exp(-(Tmin3(1) - 0.86) / 3.1104))
        NFFD_wna(2) = 30.3854 / (1 + Math.Exp(-(Tmin3(2) - 0.63) / 2.7761))
        NFFD_wna(3) = 32.5385 / (1 + Math.Exp(-(Tmin3(3) - 0.45) / 2.6121))
        NFFD_wna(4) = 30.6635 / (1 + Math.Exp(-(Tmin3(4) - 0.36) / 2.3966))
        NFFD_wna(5) = 31.2419 / (1 + Math.Exp(-(Tmin3(5) - 0.47) / 2.2458))
        NFFD_wna(6) = 30.0486 / (1 + Math.Exp(-(Tmin3(6) - 0.4) / 1.9178))
        NFFD_wna(7) = 30.9662 / (1 + Math.Exp(-(Tmin3(7) - 0.67) / 1.4936))
        NFFD_wna(8) = 30.9824 / (1 + Math.Exp(-(Tmin3(8) - 0.55) / 1.7314))
        NFFD_wna(9) = 30.1372 / (1 + Math.Exp(-(Tmin3(9) - 0.33) / 2.46))
        NFFD_wna(10) = 31.5636 / (1 + Math.Exp(-(Tmin3(10) - 0.34) / 2.548))
        NFFD_wna(11) = 31.6777 / (1 + Math.Exp(-(Tmin3(11) - 0.45) / 2.8848))
        NFFD_wna(12) = 34.409 / (1 + Math.Exp(-(Tmin3(12) - 0.78) / 2.9289))
        NFFD_wna_py12 = 34.409 / (1 + Math.Exp(-(Tmin_12 - 0.78) / 2.9289))

And for PAS:
'PAS_wna-------------------->
        PAS_wna(1) = 1 / (1 + Math.Exp(-(Tave3(1) - -2.9901) / -2.50353)) * Ppt3(1)
        PAS_wna(2) = 1 / (1 + Math.Exp(-(Tave3(2) - -1.3948) / -2.0004)) * Ppt3(2)
        PAS_wna(3) = 1 / (1 + Math.Exp(-(Tave3(3) - 0.5473) / -1.5719)) * Ppt3(3)
        PAS_wna(4) = 1 / (1 + Math.Exp(-(Tave3(4) - 2.0928) / -1.6527)) * Ppt3(4)
        PAS_wna(5) = 0.8 / (1 + Math.Exp(-(Tave3(5) - 4.078) / -1.7428)) * Ppt3(5)
        PAS_wna(6) = 0.8 / (1 + Math.Exp(-(Tave3(6) - 4.078) / -1.7428)) * Ppt3(6)
        PAS_wna(7) = 0.9 / (1 + Math.Exp(-(Tave3(7) - 2.8) / -2.3948)) * Ppt3(7)
        PAS_wna(8) = 1 / (1 + Math.Exp(-(Tave3(8) - 1.4927) / -2.8948)) * Ppt3(8)
        PAS_wna(9) = 1 / (1 + Math.Exp(-(Tave3(9) - 1.4927) / -2.8948)) * Ppt3(9)
        PAS_wna(10) = 1 / (1 + Math.Exp(-(Tave3(10) - 0.8099) / -1.6612)) * Ppt3(10)
        PAS_wna(11) = 1 / (1 + Math.Exp(-(Tave3(11) - -1.5627) / -2.4907)) * Ppt3(11)
        PAS_wna(12) = 1 / (1 + Math.Exp(-(Tave3(12) - -2.5909) / -2.2108)) * Ppt3(12)
```

**Comment by cmahony** [comment]
the problem was that the climr equation used tmin (as published) instead of tave (as per equations above). i checked the parameters themselves and they are consistent with the equation above.

**Comment by cmahony** [comment]
fixed in pull request
