### ISSUE TITLE
Add DD40 Variable

### ISSUE THREAD

**Issue by kdaust** [bcgov/climr#88]
DD40 would be a useful variable for measuring excess heat stress. The main challenge will be getting the parameter table. @cmahony do you know if one exists for DD40, or will we need to create one using station data?

**Comment by cmahony** [comment]
there are no published equations for DD40. calculating this from scratch would take a lot of doing. that said, we will ultimately want to estimate all derived variables from scratch. better, i think, for us to develop a system for calculating multiple degree days with gridded parameters. that will be a v2 thing, though.

**Comment by cmahony** [comment]
i believe we can develop the gridded parameters using Daymet. I'll open a new issue on this as future work, and leave this one open for now.
