### ISSUE TITLE
Calculate derived variables using gridded parameters

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#93]
It is likely that we can use Daymet to calculate derived variables using gridded parameters. this would improve on the ClimateBC approach of using universal parameters for North America. likely do this next summer. 
some details: 
- [ ] Daymet includes snow water equivalent, which we can use to more directly estimate monthly precipitation as snow. 
- [ ] calculate degree day parameters in ~5-DD intervals and see if we can reliably interpolate for user-defined degree days.

**Comment by kdaust** [comment]
Closing as we'll use issue #96 for all variable related stuff.
